branches:
  except:
  - "/^wip/"
  - "/^dependabot/"
language: node_js
node_js: '12'
dist: xenial
env:
  global:
  - COVERALLS_PARALLEL=true

jobs:
  include:
    -
      name: "Unit Tests"
      install:
      - pyenv global 3.7.1
      - pip install --user torch transformers
      - travis_retry npm ci
      script:
      - npm run lint
      #- npm run doc
      - TZ="America/Los_Angeles" npx nyc ts-node -T ./test/unit
      after_success: npm run coverage
    -
      name: "Dialogue Agent Tests"
      install:
      - travis_retry npm ci
      script:
      - TZ="America/Los_Angeles" npx nyc ts-node -T ./test/agent
      after_success: npm run coverage
    -
      name: "Engine Tests"
      install:
      - travis_retry npm ci
      script:
      - TZ="America/Los_Angeles" npx nyc ts-node -T ./test/engine
      after_success: npm run coverage
    -
      name: "Command-line Tests"
      install:
      - travis_retry npm ci
      script: npx nyc ./test/cmdline.sh
      after_success: npm run coverage
    -
      name: "Starter Code Tests (Basic)"
      install:
      - pyenv global 3.7.1
      - ./travis/install-starter-deps.sh
      - travis_retry npm ci
      script: npx nyc ./test/basic-starter.sh
      after_success: npm run coverage
    -
      name: "Starter Code Tests (Schema.org)"
      install:
      - pyenv global 3.7.1
      - ./travis/install-starter-deps.sh
      - travis_retry npm ci
      script: npx nyc ./test/schemaorg-starter.sh
      after_success: npm run coverage
    - name: "Starter Code Tests (Wikidata)"
      install:
      - pyenv global 3.7.1
      - ./travis/install-starter-deps.sh
      - travis_retry npm ci
      script: npx nyc ./test/wikidata-starter.sh
      after_success: npm run coverage
    -
      name: "Starter Code Tests (MultiWOZ)"
      install:
      - pyenv global 3.7.1
      - ./travis/install-starter-deps.sh
      - travis_retry npm ci
      script: npx nyc ./test/multiwoz-starter.sh
      after_success: npm run coverage

notifications:
  webhooks: https://coveralls.io/webhook
  slack:
    secure: IgwEjeN5cfZMm+zOnxiL7Gd1F4JYL+CFlNoEO5NbQ9Nl+OPRF3DI33mumC7AvBx32i0xmd62MYdLs8hSKQfmrv/amq1mxEqpnvATNh58v9SOMzAw5zscf5TMgSD4L3jzAQ4kLkws1DCxq8TaaukErQYVIUU0n6ILJQ3UuUGPjKLX7R2CwjzPVNeCbBxyJ6c/kwmVOEn//E5be+Y3g044AfeJZ8Q99oVIKqzgxI+kkDwuc4bkbQwP+p6hDcXAuy13ewoTz/f6oAUjcgJUwKUAe0LiVVS46aXT1ftBUQN8wA/KEgC4TdMsfmOI4XbzW9g7xhngAZ5DdB+wJ2R2TGhpqSjZ7yCQGMH4yM/2QU4dMEQUd1A9H0bYCaC449yp+WVIDz78bC4GQA1UA8RzeM8EHb5GHRQu1LloHTVSdVoTjbngPMFv6lJj7AjhAfPgi7IyO2DIp2J7f2/2FdxRVIq+TRwBNQdo1/G+XvQFNtev5o5ANiIa/r+fmE5i1yi0ZVfpe3ojerrTxArtn6VRazO7SdiyW+injMSx+NlGj3qtJVGNrzQNlC9lpOMN/Y4Y3NWSnlNumRNAxBGEUS7hnRPBRrkovUe6mdLRI4oSkVl4cwR8XNh+R31IJl9g7XpehBmkXWh+gq44S82Y+dTvbvOCidgd55AQNVTOp0XE//hE5TQ=
deploy:
  provider: npm
  skip_cleanup: true
  email: gcampagn@cs.stanford.edu
  api_key:
    secure: VE60YDgM3hlvMODrKdyU2dKtlJ5+ewZ/ns5oFY38sjJbBhqXBF/pxd9Ky/4ORYjGQvEG3I3d+eiI4EVfXYsZEDuSAgz1zvx7DnX+H1OHy7aJigIvg5hqpNSCcKeC7MAEqpYFBt495ZyvYHDqUsrmlxMwKY65KXv76RoYVPFh9ZwPpE2kehYKNMYNzpSPgARDW44+Zordyen6wYukaYS0Wen5vFouCwZiFS57KLOQZk4VzLPSIqLH1NNAC8fnV7l6JffbFjhf1ufQqr7gh17CG/wAXsbHNf2C5hI59+wdZ04oJhxdcjp/Tt2h21uuQb/zyGC+Yv4aDLH/yVvUyZ527PgiyeEhJpEgAeX0SfzWLc5cbx30/LWNWYd5Jv5qTiRiVxcr8s3+XVi1f5mDJcjhe+0PcGe9j+TfsaYHOlBhmwlK1uV8zmFzYlIorU47OLu0CWFDNOmT2GRvFax9mKFmr/aS2UecVtCqe+e4/9hJCguQPdDqIpuRgFdkvtztPCuikFAvaUpLxhwyIfhSqiMDcKEZve55dmX2GAc6sRQ7hOO85inzM4GlF8HyNU29zchT0w/gMrqdxQfpzCbW9z8nfkQzWUwD0kNPVEIFTd6gm0GygcQtHn8QgX2FBEyutHqf3afQGDIG36gKNWi82td96D7RxRIDr0A6Qk1WGy/Khe4=
  on:
    tags: true
    repo: stanford-oval/genie-toolkit
